# Generated by Django 5.1.4 on 2024-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "GENDER",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("AGE", models.IntegerField()),
                ("SMOKING", models.IntegerField()),
                ("YELLOW_FINGERS", models.IntegerField()),
                ("ANXIETY", models.IntegerField()),
                ("PEER_PRESSURE", models.IntegerField()),
                ("CHRONIC_DISEASE", models.IntegerField()),
                ("FATIGUE", models.IntegerField()),
                ("ALLERGY", models.IntegerField()),
                ("WHEEZING", models.IntegerField()),
                ("ALCOHOL_CONSUMING", models.IntegerField()),
                ("COUGHING", models.IntegerField()),
                ("SHORTNESS_OF_BREATH", models.IntegerField()),
                ("SWALLOWING_DIFFICULTY", models.IntegerField()),
                ("CHEST_PAIN", models.IntegerField()),
                (
                    "LUNG_CANCER",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
            ],
        ),
    ]
